---
- name: restart sssd
  systemd:
    name: sssd
    state: restarted
    enabled: yes

- name: restart httpd
  systemd:
    name: httpd
    state: restarted
    enabled: yes

- name: restart ntpd
  systemd:
    name: ntpd
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: restart snmp
  systemd:
    name: snmpd
    state: restarted
    enabled: yes

- name: restart firewall
  systemd:
    name: firewalld
    state: restarted
    enabled: yes

- name: restart rsyslog
  systemd: 
    name: rsyslog 
    state: restarted 
    enabled: yes

- name: newaliases
  command: newaliases
 
- name: restart postfix
  systemd: 
    name: postfix 
    state: restarted 
    enabled: yes
